output: mythxOutput.json
format: json

analyze:
    mode: standard
    min-severity: medium
    remappings:
        - "@openzeppelin/=./node_modules/@openzeppelin/"
        - "@balancer-labs/=./node_modules/@balancer-labs/"